[FileDialog]
history=file:///home/scriptwiz/Downloads/item, file:///home/scriptwiz/Downloads/Telegram Desktop, file:///home/scriptwiz/Documents/PUBLIC OB NURSING NOTES-20250531T155913Z-1-001/newBrain/Excalidraw, file:///home/scriptwiz/Documents/doiff, file:///home/scriptwiz/Downloads
lastVisited=file:///home/scriptwiz/Downloads/Telegram Desktop
qtVersion=6.9.1
shortcuts=file:, file:///home/scriptwiz
sidebarWidth=94
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\x3\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2<\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\x15\0\0\0\x1\0\0\0\0\0\0\0u\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0u\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
