add_newline = true

# format = """
# $time\
# $username\
# $directory\
# $character"""
format = """
[┌─](bold green) $battery$time$username$directory
[└─>](bold green) """
right_format = """$git_branch $git_status $git_state $cmd_duration"""

[battery]
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󰂂'

[[battery.display]]
threshold = 10

[time]
disabled = false
format = '[\[🕙$time\]]($style) '
time_format = '%-I:%M%p'  # Matches zsh's %_I:%M%P (e.g., 3:45pm)

# Username module
[username]
disabled = false
show_always = true
format = '[$user]($style) in '

# Directory module
[directory]
disabled = false
format = '[\[$path\]]($style) '

[hostname]
ssh_symbol = " "
format = "[$ssh_symbol $hostname]($style) "

[git_branch]
symbol = ""
format =  "[$symbol $branch (:$remote_branch)]($style)"

[git_status]
style = "bold blue"
format = "[$modified$deleted$untracked$ahead_behind]($style) "
modified = " "
deleted = " "
untracked = " "
ahead = " "
behind = " "
up_to_date = " "

[cmd_duration]
min_time = 20_000

